### ISSUE TITLE
I18N support?

### ISSUE THREAD

**Issue by johnfelipe** [analysis-tools-dev/static-analysis#1061]
Can I contribute if you share strings in yml, Json or pot file format for es, de, de and it

**Comment by mre** [comment]
Hey John,
that's an interesting idea. However I'm not sure I fully understand. How would we use the translations in this repo? Would we list all tools multiple times in different languages?
We could add internationalization support to [the website](https://github.com/analysis-tools-dev/website/), even though it would be a lot of work to maintain.
Curious about your thoughts.

**Comment by johnfelipe** [comment]
If you parse all strings into yml, Json or something I want to translate in different languages

**Comment by mre** [comment]
Yes, the rendering part can certainly be done.
The issue is that I don't know how to maintain the translations in the long run.
For example, if someone updates a tool description, we would have to update the translations as well. I don't think most contributors would care to update them themselves, so we'd have to either remind them or do it ourselves.
The other question is still how we're going to present the translations to our users. Would we render all of the different translations in the same repository or create separate repositories for them?
Is there any other list on Github that does this? I'd be thankful for any links or thoughts.

**Comment by mre** [comment]
At this point I don't see how we can solve the problems mentioned in my previous comment. I think i18n would add quite a bit of maintenance overhead and I don't think we can handle it at the moment. Let's revisit this at at a later point in time. Thanks for the suggestion and the help you offered @johnfelipe. 👍

**Comment by johnfelipe** [comment]
Dear I want to be that contributor, I want to translate in my languages es,
de, fr and it, strings and markdown
Pls begin and I will do it for long term dear.
